config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home', as: :home
  get '/index', to: "welcome#index", as: :welcome

  resources :waypoints, only: [:create, :update, :destroy]
  resources :colleges, except: [:destroy, :show]
  resources :users, except: [:destroy] do 
    resources :rides
  end

  get '/rides/:id/book', to: 'rides#book', as: :book_ride
  get '/rides', to: 'rides#search', as: :search_rides
  get '/rides/:id', to: 'rides#search_show', as: :search_ride
  get '/users/:id/toggle_active', to: 'users#toggle_active', as: :user_toggle_active
  get '/colleges/:id/toggle_active', to: 'colleges#toggle_active', as: :college_toggle_active
  get 'user/:user_id/rides/:id/toggle_active', to: 'rides#toggle_active', as: :ride_toggle_active
  get '/ride/:ride_id/waypoints/new', to: 'waypoints#new', as: :new_ride_waypoints
  post '/ride/:ride_id/waypoints', to: 'waypoints#create', as: :ride_waypoints
  delete '/waypoints/:id', to: 'waypoints#destroy'
  
  get '/logout', to: 'authenticate#logout', as: :logout
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :iduff,
    presence: { message: "não pode ficar vazio" }
  validates :iduff, 
    format: { with: /\d{11}/s, message: 'é inválido' }, 
    uniqueness: { message: 'é inválido' }
  validates :active, :admin, inclusion: { in: [true, false] }, on: :update

  has_many :rides, through: :reservation

  def rides
    Ride.where(driver_id: self.id)
  end

  def active?
    self.active
  end

  def admin?
    self.admin
  end

  def self.search_query(query)
    if query.nil?
      User.all.order(:name)
    else
      User.where("name LIKE :q OR iduff LIKE :q OR iduff LIKE :q", q: "#{query}%").order(:name).limit(20)
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update toggle_active rides ]

  def index
    @users = User.search_query(params[:q])
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @users }
    end
  end

  def rides
    @rides = @logged_user.rides
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_create_params)
    @user.active = true
    if @user.save
      redirect_to users_url, notice: "Usuário criado com sucesso."
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def update
    if @user.update(user_update_params)
      redirect_to users_url, notice: "Usuário atualizado com sucesso." 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def toggle_active
    @users = User.search_query(nil)
    if @user.update!(active: not(@user.active?))
      redirect_to users_url, notice: "Usuário #{@user.active? ? "reativado" : "desativado"} com sucesso." 
    else 
      render :index, status: :unprocessable_entity 
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_update_params
      params.require(:user).permit(:name, :iduff, :active, :admin)
    end

    def user_create_params
      params.require(:user).permit(:name, :iduff, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def pretty_iduff iduff
    iduff.insert(3, '.').insert(7, '.').insert(11, '-')
  end
end

app/views/users/_form.html.erb
<% if user.errors.any? %>
  <div id="error_explanation">
    <h2>Alguns erros proibiram esse usuário de ser salvo:</h2>
    <ul>
      <% user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<section class='mb-5'>
  <div class='d-flex flex-column w-25 ms-3'>
    <%= form_with model: user do |form| %>
      <% if @logged_user.admin? %>
        <%= form.label :name, "Nome:", class: 'mb-2 form-label' %>
        <%= form.text_field :name, class: 'form-control mb-3 form-control-sm' %>
        <%= form.label :iduff, "IdUFF:", class: 'mb-2' %>
        <%= form.text_field :iduff, placeholder: '111.111.111-11', class: 'form-control mb-3 form-control-sm' %>
        <% if user.id %>
          <%= form.label :password, "Senha:", class: 'mb-2' %>
          <%= form.password_field :password, class: 'form-control mb-3 form-control-sm'%>
        <% end %>
        
        <%= form.label :admin, "Admin:", class: 'mb-4 me-2' %>
        <%= form.check_box :admin, class: 'form-check-input mb-4' %>
      <% else %>
        <%= form.label :name, "Nome:", class: 'mb-2' %>
        <%= form.text_field :name, readonly: true, class: 'form-control mb-3 form-control-sm' %>
        <%= form.label :iduff, "IdUFF:", class: 'mb-2' %>
        <%= form.text_field :iduff, readonly: true, class: 'form-control mb-3 form-control-sm' %>
        <%= form.label :password, "Senha:", class: 'mb-2' %>
        <%= form.password_field :password, class: 'form-control mb-3 form-control-sm'%>
      <% end %>
      <div class="d-flex">
        <%= form.submit 'Salvar', class: 'btn btn-success me-4' %>
        <%= link_to 'Voltar', users_path, class: 'btn btn-secondary' %>
      </div>
    <% end %>  
  </div>
</section>
<%= javascript_pack_tag 'masks'%>

app/views/users/_user_card.html.erb
<div class='card mb-4' id='card-<%= user.id %>'>
  <div class='card-body d-flex flex-row justify-content-between container align-items-center'>
    <div class='d-flex flex-column justify-content-between'>
      <div class='d-flex align-items-center'>
        <h4 class='card-title mb-3 mt-3 me-3'><%= user.name %></h4>
        <p class="fw-bold text-danger m-0"><%= user.active? ? nil : "Desativado" %></p>
      </div>
      <h6 class="card-subtitle mb-3 ms-2 text-muted">IdUFF: <%= pretty_iduff(user.iduff) %></h6>
    </div>
    <div class='d-flex flex-column w-15'>
      <% if user.id != logged_user.id %>
        <%= link_to 'Editar', edit_user_path(user), class: 'btn btn-outline-warning mb-3' %>
        <% if user.active? %>
          <%= link_to 'Desativar', user_toggle_active_path(user), data: {confirm: "Tem certeza?"}, class: 'btn btn-outline-danger', id: "toggle-active-#{user.id}" %>
        <% else %>
          <%= link_to 'Reativar', user_toggle_active_path(user), data: {confirm: "Tem certeza?"}, class: 'btn btn-outline-success', id: "toggle-active-#{user.id}" %>
        <% end %>
      <% else %>
        <%= link_to 'Editar', edit_user_path(user), class: 'btn btn-outline-warning' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editar Usuário</h1>
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class='d-flex flex-row justify-content-between align-items-center'>
  <h1>Usuários</h1>
  <%= link_to 'Novo', new_user_path, class: 'btn btn-primary' %>
</div>

<section class='d-flex flex-column align-items-center'> 
  <div class='w-75 p-3'>
    <%= form_with url: users_url, method: :get do |form| %>
      <div class="autocomplete">
        <div class='input-group'>
          <%= form.text_field :q, class:'form-control', placeholder:'Nome ou IdUFF', autocomplete: 'off' %>
          <%= form.submit 'Procurar', class:'btn btn-outline-info' %>
        </div>
      </div>
    <% end %>
  </div>

  <ul class='w-75 p-3'>
    <% @users.each do |user| %>
      <%= render 'user_card', user: user, logged_user: @logged_user %>
    <% end %>
  </ul>
</section>

<%= javascript_pack_tag 'users' %>

app/views/users/new.html.erb
<h1>Novo Usuário</h1>
<%= render 'form', user: @user %>