config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home', as: :home
  get '/index', to: "welcome#index", as: :welcome

  resources :waypoints, only: [:create, :update, :destroy]
  resources :colleges, except: [:destroy, :show]
  resources :users, except: [:destroy] do 
    resources :rides
  end

  get '/rides/:id/book', to: 'rides#book', as: :book_ride
  get '/rides', to: 'rides#search', as: :search_rides
  get '/rides/:id', to: 'rides#search_show', as: :search_ride
  get '/users/:id/toggle_active', to: 'users#toggle_active', as: :user_toggle_active
  get '/colleges/:id/toggle_active', to: 'colleges#toggle_active', as: :college_toggle_active
  get 'user/:user_id/rides/:id/toggle_active', to: 'rides#toggle_active', as: :ride_toggle_active
  get '/ride/:ride_id/waypoints/new', to: 'waypoints#new', as: :new_ride_waypoints
  post '/ride/:ride_id/waypoints', to: 'waypoints#create', as: :ride_waypoints
  delete '/waypoints/:id', to: 'waypoints#destroy'
  
  get '/logout', to: 'authenticate#logout', as: :logout
  
end

app/views/shared/_navbar.html.erb
<nav class="navbar border navbar-expand-lg navbar-light bg-light mb-3">
  <div class="container">
    <ul class="nav justify-content-start">
      <li class="nav-item">
        <%= link_to image_tag('logo_uff.png', width:"60", height:"30"), home_path, class:"navbar-brand", value:"Coranas" %>
      </li>

    <% if @logged_user.admin? %>

      <li class="nav-item">
        <%= link_to 'Dashboard', home_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Usuários", users_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Campi", colleges_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Corridas", search_rides_path, class:"nav-link" %>
      </li>


    <% else %>

      <li class="nav-item">
        <%= link_to 'Dashboard', home_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Minhas Caronas', user_rides_path(@logged_user), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Pesquisar Caronas", search_rides_path, class:"nav-link" %>
      </li>

    <% end %>

    </ul>
    <div>
      <p class='m-0 me-2'><%= @logged_user.name %></p>
      <%= link_to "Sair", logout_path, class:"nav-link" %>
    </div>
  </div>
</nav>