config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home', as: :home
  get '/index', to: "welcome#index", as: :welcome

  resources :waypoints, only: [:create, :update, :destroy]
  resources :colleges, except: [:destroy, :show]
  resources :users, except: [:destroy] do 
    resources :rides
  end

  get '/rides/:id/book', to: 'rides#book', as: :book_ride
  get '/rides', to: 'rides#search', as: :search_rides
  get '/rides/:id', to: 'rides#search_show', as: :search_ride
  get '/users/:id/toggle_active', to: 'users#toggle_active', as: :user_toggle_active
  get '/colleges/:id/toggle_active', to: 'colleges#toggle_active', as: :college_toggle_active
  get 'user/:user_id/rides/:id/toggle_active', to: 'rides#toggle_active', as: :ride_toggle_active
  get '/ride/:ride_id/waypoints/new', to: 'waypoints#new', as: :new_ride_waypoints
  post '/ride/:ride_id/waypoints', to: 'waypoints#create', as: :ride_waypoints
  delete '/waypoints/:id', to: 'waypoints#destroy'
  
  get '/logout', to: 'authenticate#logout', as: :logout
  
end

app/models/college.rb
class College < ApplicationRecord
  validates :name, :address, :neighborhood, :city, :phone_number, :cep, :active, presence: true, on: :create
  validates :active, inclusion: [true, false], on: :update
  validates :phone_number, length: {is: 11}, format: { with: /\d{2}\d{4}\-\d{4}/s}
  validates :cep, length: {is: 9}, format: {with: /\d{5}\-\d{3}/s}

  def active?
    self.active
  end

end

app/controllers/college_controller.rb
class CollegeController < ApplicationController
  before_action :set_action, only: [:show, :update, :destroy]
  
  def index
    @colleges = College.all
  end

  def show
  end

  def create 
    @college = College.new(college_params)
    @college.active ||= true
    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'Campus criado com sucesso.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @college.update(colleg_params)
        format.html {redirect_to: @college}
      else
        format.html {redirect_to: :edit}
      end
    end
  end

  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'Campus excluído com sucesso.' }
    end
  end


  
  private
  def set_college
    College.find params[:id]
  end
  def college_params
    params.require(:college).permit(:name, :address, :neighborhood, :city, :phone_number, :cep, :active)
  end
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:edit, :update, :toggle_active]
  
  def index
    @colleges = College.all.order(:name)
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @colleges }
    end
  end

  def new
    @college = College.new
  end

  def edit
  end

  def create 
    @college = College.new(college_params)
    @college.active ||= true
    respond_to do |format|
      if @college.save
        format.html { redirect_to colleges_url, notice: 'Campus criado com sucesso.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @college.update(college_params)
      redirect_to colleges_url
    else
      render :edit
    end
  end

  def toggle_active
    if @college.update(active: not(@college.active?))
      redirect_to colleges_url, notice: "Campus #{@college.active? ? "reativado" : "desativado"} excluído com sucesso."
    else
      render :index, status: :unprocessable_entity
    end
  end

  private
  def set_college
    @college = College.find params[:id]
  end

  def college_params
    params.require(:college).permit(:name, :address, :neighborhood, :city, :phone_number, :cep, :active)
  end
end

app/helpers/college_helper.rb
module CollegeHelper
  def full_address college
    "#{college.address}, #{college.neighborhood}, #{college.city} - #{college.cep}"
  end
end

app/views/colleges/_campus_card.html.erb
<div class='card'>
  <div class='card-body'>
    <h5 class='card-title'><%= college.name %></h5>
    <h6 class=1card-subtitle mb-2 text-muted1><%= full_address(college) %></h6>
  </div>
  <div class="card-footer">
    <%= link_to 'Editar', edit_college_path(college), method: :put, class: 'btn btn-warning' %>
    <%= link_to 'Deletar', college_path(college), method: :delete, data: {confirm: "Tem certeza?"}, class: 'btn btn-danger'%>
  </div>
</div>

app/views/colleges/_college_card.html.erb
<div class='card mb-4'>
  <div class='card-body d-flex flex-row justify-content-between container align-items-center'>
    <div class='d-flex flex-column justify-content-between'>
      <div class='d-flex align-items-center'>
        <h4 class='card-title mb-3 mt-3 me-3'><%= college.name %></h4>
        <p class="fw-bold text-danger m-0"><%= college.active? ? nil : "Desativado" %></p>
      </div>
      <h6 class='card-subtitle mb-3 ms-2 text-muted'>Endereço: <%= full_address(college) %></h6>
      <h6 class="card-subtitle mb-3 ms-2 text-muted">Número: <%= college.phone_number %></h6>
    </div>
    <div class='d-flex flex-column'>
      <%= link_to 'Editar', edit_college_path(college), class: 'btn btn-outline-warning mb-3' %>
      <% if college.active? %>
        <%= link_to 'Desativar', college_toggle_active_path(college), data: {confirm: "Tem certeza?"}, class: 'btn btn-outline-danger' %>
      <% else %>
        <%= link_to 'Reativar', college_toggle_active_path(college), data: {confirm: "Tem certeza?"}, class: 'btn btn-outline-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/colleges/_form.html.erb
<% if college.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(college.errors.count, "error") %> proibiram esse campus de ser salvo:</h2>
    <ul>
      <% college.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<section class='mb-5'>
  <div class='d-flex flex-column w-25 ms-3'>
    <%= form_with model: college do |form| %>
      <%= form.label :name, "Nome:", class:'form-label' %>
      <%= form.text_field :name, class:'form-control mb-3 form-control-sm'%>
      <%= form.label :address, "Endereço:", class:'form-label' %>
      <%= form.text_field :address, class:'form-control mb-3 form-control-sm' %>
      <%= form.label :neighborhood, "Bairro:", class:'form-label' %>
      <%= form.text_field :neighborhood, class:'form-control mb-3 form-control-sm' %>
      <%= form.label :city, "Cidade:", class:'form-label' %>
      <%= form.text_field :city, class:'form-control mb-3 form-control-sm'%>
      <%= form.label :phone_number, "Número:", class:'form-label' %>
      <%= form.telephone_field :phone_number, placeholder: '(00) 0000-0000', class:'form-control mb-3 form-control-sm' %>
      <%= form.label :cep, "CEP:", class:'form-label' %>
      <%= form.text_field :cep, placeholder: '00000-000', class:'form-control mb-3 form-control-sm' %>
      <%= form.label :active, "Ativo:", class:'form-label' %>
      <%= form.check_box :active, checked: true, class:'form-check-input' %>
      <div class="d-flex">
        <%= form.submit 'Salvar', class: 'btn btn-success me-4' %>
        <%= link_to 'Voltar', colleges_path, class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</section>
<!-- <%= javascript_pack_tag 'masks'%> -->

app/views/colleges/edit.html.erb
<h1>Atualizar Campus</h1>
<%= render 'form', college: @college %>

app/views/colleges/index.html.erb
<p id="notice"><%= notice %></p>

<div class='d-flex flex-row justify-content-between align-items-center'>
  <h1>Campi</h1>
  <%= link_to 'Novo', new_college_path, class: 'btn btn-primary' %>
</div>

<section class='d-flex justify-content-center'>  
  <ul class='w-75 p-3'>
    <% @colleges.each do |college| %>
      <%= render 'college_card', college: college %>
    <% end %>
  </ul>
</section>

app/views/colleges/new.html.erb
<h1>Novo Campus</h1>
<%= render 'form', college: @college %>