config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#home', as: :home
  get '/index', to: "welcome#index", as: :welcome

  resources :waypoints, only: [:create, :update, :destroy]
  resources :colleges, except: [:destroy, :show]
  resources :users, except: [:destroy] do 
    resources :rides
  end

  get '/rides/:id/book', to: 'rides#book', as: :book_ride
  get '/rides', to: 'rides#search', as: :search_rides
  get '/rides/:id', to: 'rides#search_show', as: :search_ride
  get '/users/:id/toggle_active', to: 'users#toggle_active', as: :user_toggle_active
  get '/colleges/:id/toggle_active', to: 'colleges#toggle_active', as: :college_toggle_active
  get 'user/:user_id/rides/:id/toggle_active', to: 'rides#toggle_active', as: :ride_toggle_active
  get '/ride/:ride_id/waypoints/new', to: 'waypoints#new', as: :new_ride_waypoints
  post '/ride/:ride_id/waypoints', to: 'waypoints#create', as: :ride_waypoints
  delete '/waypoints/:id', to: 'waypoints#destroy'
  
  get '/logout', to: 'authenticate#logout', as: :logout
  
end

app/models/ride.rb
class Ride < ApplicationRecord
  has_many :waypoints, dependent: :destroy
  belongs_to :driver, class_name: :User
  has_many :users, through: :reservation

  validates :time, :date, :seats, :price, :college_id, :driver_id, presence: true, on: :create
  validates :seats, numericality: { greater_than: 0, only_integer: true } 
  validates :to_college, :active, :full, inclusion: { in: [false, true] }

  validate :passagers_cannot_be_greater_than_seats, on: :update
  validate :cannot_be_in_past


  def self.deactivate_past_rides user
    rides = Ride.where(driver_id: user.id)
    rides.each do |ride| 
      if ride.date < Date.today or (ride.date == Date.today and ride.time < Time.now)
        ride.update(active: false) 
      end
    end
  end

  def self.availables
    Ride.all.where(
      'active = :active AND rides.full = :full AND (date > :date OR (date = :date AND time > :time))', 
      active: true, full: false, date: Date.today, time: Time.now
    ).order(:date)
  end

  def self.search (query)
    if query[:departure_kind].nil? and query[:destination_kind].nil?
      Ride.availables
    else
      if query[:ride][:neighborhood].present?
        if query[:destination_kind] == 'college'
          query[:destination] = query[:ride][:neighborhood]

        elsif query[:departure_kind] == 'college'
          query[:departure] = query[:ride][:neighborhood]
        end
      end
      Ride.availables.where('destination_neighborhood LIKE ? AND departure_neighborhood LIKE ?',  
          "#{query[:destination]}%", "#{query[:departure]}%")
    end
  end
  
  def book_seat
    self.number_of_passagers += 1
    return update(full: (self.seats == self.number_of_passagers), number_of_passagers: self.number_of_passagers)
  end

  def departure
    self.waypoints.where(kind: :departure).first
  end

  def destination
    self.waypoints.where(kind: :destination).first
  end

  def stops
    self.waypoints.where(type: :stop).order(:order)
  end

  def college
    College.find(self.college_id)
  end

  def active?
    self.active
  end

  def create_destination(params)
    if self.to_college
      college = self.college
      params[:destination_address] = college.address
      params[:destination_neighborhood] = college.neighborhood
      params[:destination_city] = college.city
    end
    destination = Waypoint.new(
      address: params[:destination_address],
      city: params[:destination_city],
      neighborhood: params[:destination_neighborhood],
      order: 0,
      is_college: self.to_college,
      kind: :destination,
      ride_id: self.id
    )
    destination.save
    return destination
  end

  def create_departure(params)
    unless self.to_college
      college = self.college
      params[:departure_address] = college.address
      params[:departure_neighborhood] = college.neighborhood
      params[:departure_city] = college.city
    end
    departure = Waypoint.new(
      address: params[:departure_address],
      city: params[:departure_city],
      neighborhood: params[:departure_neighborhood],
      order: 0,
      is_college: not(self.to_college),
      kind: :departure,
      ride_id: self.id
    )
    departure.save
    return departure
  end

  def update_destination params
    if self.to_college
      college = self.college
      params[:destination_address] = college.address
      params[:destination_neighborhood] = college.neighborhood
      params[:destination_city] = college.city
    end
    destination = self.destination
    destination.update(
      address: params[:destination_address],
      city: params[:destination_city],
      neighborhood: params[:destination_neighborhood],
      is_college: self.to_college
    )
    return destination
  end

  def update_departure params
    unless self.to_college
      college = self.college
      params[:departure_address] = college.address
      params[:departure_neighborhood] = college.neighborhood
      params[:departure_city] = college.city
    end
    departure = self.departure
    departure.update(
      address: params[:departure_address],
      city: params[:departure_city],
      neighborhood: params[:departure_neighborhood],
      is_college: not(self.to_college)
    )
    return departure
  end

  def ordered_waypoints
    self.waypoints.order(:order)
  end


  private 

  def passagers_cannot_be_greater_than_seats
    if self.seats < self.number_of_passagers
      errors.add(:number_of_passagers, "can't be greater than seats")
    end
  end

  def cannot_be_in_past
    if self.time and self.date
      if self.date < Date.today 
        errors.add(:date, 'cannot be in the past')
      end
      if self.date == Date.today and self.time < Time.now
        errors.add(:time, 'cannot be in the past')
      end
    end
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :set_ride, only: %i[ show edit update destroy book toggle_active ]
  before_action :set_user, only: %i[ index show new edit create destroy toggle_active ]

  def search
    @rides = Ride.search(params).where.not(driver: @logged_user).order(date: :desc)
  end

  def book
    if @ride.book_seat
      redirect_to ride_url(@ride), notice: "Ride was successfully booked."
    else
      render :search, status: :unprocessable_entity
    end
  end

  def index
    Ride.deactivate_past_rides(@user)
    @rides = Ride.all.where(driver: @user).order(:date, :time)
  end

  def show
  end

  def new
    @ride = Ride.new
  end

  def edit
  end

  def create
    @ride = Ride.new(ride_params)
    @ride.driver_id = @user.id
    if @ride.to_college
      @ride.destination_neighborhood = @ride.college.neighborhood
    else
      @ride.departure_neighborhood = @ride.college.neighborhood
    end
    if @ride.save
      @departure = @ride.create_departure(departure_ride_params)
      @destination = @ride.create_destination(destination_ride_params)
      if @departure.errors.any? or @destination.errors.any?
        @ride.destroy
        @departure.destroy if @departure.errors.any?
        @destination.destroy if @destination.errors.any?
        render :new, status: :unprocessable_entity 
      else  
        redirect_to new_ride_waypoints_url(@ride), notice: "Carona criada com sucesso." 
      end
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def update
    if @ride.update(ride_params)
      @destination = @ride.update_destination(destination_ride_params)
      @departure = @ride.update_departure(departure_ride_params)
      if @departure.errors.any? or @destination.errors.any?
        render :edit, status: :unprocessable_entity
      else
        redirect_to new_ride_waypoints_url(@ride), notice: "Corrida atualizada com sucesso."
      end
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @ride.destroy
    redirect_to user_rides_url(@user), notice: "Corrida apagada com sucesso."
  end

  def toggle_active
    if @ride.update(active: not(@ride.active?))
      redirect_to user_rides_url(@user), notice: "Corrida #{@ride.active? ? "reativada" : "desativada"} com sucesso." 
    else
      render :index
    end
  end
  

  private
    def set_ride
      @ride = Ride.find(params[:id])
    end

    def set_user 
      @user = User.find(params[:user_id])
    end

    def ride_params
      params.require(:ride).permit(
        :price, 
        :seats, 
        :observation, 
        :college_id, 
        :time, 
        :date, 
        :to_college, 
        :destination_neighborhood,
        :departure_neighborhood
      )
    end

    def destination_ride_params
      params.require(:ride).permit( 
        :destination_neighborhood, 
        :destination_address,
        :destination_city
      )
    end

    def departure_ride_params
      params.require(:ride).permit(
        :departure_neighborhood,
        :departure_address,
        :departure_city
      )
    end
end

app/helpers/rides_helper.rb
module RidesHelper
  def address_format(waypoint)
    "#{waypoint.address}, #{waypoint.neighborhood}"
  end

  def full_address_format(waypoint)
    "#{waypoint.address}, #{waypoint.neighborhood}, #{waypoint.city}"
  end
end

app/views/rides/_form.html.erb
<style>
  .tab {
    display: none;
  }
  input.invalid {
    background-color: #ffdddd;
  }
</style>

<% if ride.errors.any? %>
  <div id="error_explanation">
    <h2>Alguns erros impediram de cadastrar essa corrida:</h2>
    <ul>
      <% ride.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<section class='mb-5'>
  <div class='d-flex flex-column w-25 ms-3'>
    <%= form_with url: url, model: ride, id:'regForm' do |form| %>
    
      <div class='tab'>Origem:
        <div class='mb-2 mt-2 to-college'>
          <%= form.label :to_college, "Campus:", class: 'mb-3 form-label', for: :to_college_departure %>
          <%= form.check_box :to_college, class: 'form-check-input mb-3', id: :to_college_departure %>
        </div>
        <div id='departure-input'>
          <%= form.label :departure_address, "Endereço:", class: 'mb-2 form-label' %>
          <%= form.text_field :departure_address, class: 'form-control mb-3 form-control-sm' %>
          <%= form.label :departure_neighborhood, "Bairro:", class: 'mb-2 form-label' %>
          <%= form.text_field :departure_neighborhood, class: 'form-control mb-3 form-control-sm' %>
          <%= form.label :departure_city, "Cidade:", class: 'mb-2 form-label' %>
          <%= form.text_field :departure_city, class: 'form-control mb-3 form-control-sm' %>
        </div>
      </div>

      <div class='tab'>Destino
        <div class='mb-2 mt-2 to-college'>
          <%= form.label :to_college, "Campus:", class: 'mb-3 form-label', for: :to_college_destination %>
          <%= form.check_box :to_college, class: 'form-check-input mb-3', id: :to_college_destination %>
        </div>
        <div id='destination-input'>
          <%= form.label :destination_address, "Endereço:", class: 'mb-2 form-label' %>
          <%= form.text_field :destination_address, class: 'form-control mb-3 form-control-sm' %>
          <%= form.label :destination_neighborhood, "Bairro:", class: 'mb-2 form-label' %>
          <%= form.text_field :destination_neighborhood, class: 'form-control mb-3 form-control-sm' %>
          <%= form.label :destination_city, "Cidade:", class: 'mb-2 form-label' %>
          <%= form.text_field :destination_city, class: 'form-control mb-3 form-control-sm' %>
        </div>
      </div>

      <div class='tab'>Detalhes da corrida:
        <%= form.label :seats, "Assentos:", class: 'mb-2 form-label' %>
        <%= form.number_field :seats, class: 'form-control mb-3 form-control-sm' %>
        <%= form.label :price, "Preço (por passageiro):", class: 'mb-2 form-label' %>
        <%= form.number_field :price, class: 'form-control mb-3 form-control-sm' %>
        <%= form.label :date, "Data:", class: 'mb-2 form-label' %>
        <%= form.date_field :date, class: 'form-control mb-3 form-control-sm' %>
        <%= form.label :time, "Horário:", class: 'mb-2 form-label' %>
        <%= form.time_field :time, class: 'form-control mb-3 form-control-sm' %>
        <%= form.label :observation, "Observações:", class: 'mb-2 form-label' %>
        <%= form.text_area :observation, size: '70x4', class: 'form-control mb-3 form-control-sm' %>
      </div>

      <div style="overflow:auto;" class="d-flex mb-4">
        <%= link_to 'Voltar', user_rides_path(user), class: 'btn btn-secondary me-4', id:'backBtn' %>
        <button type="button" id="prevBtn" class='btn btn-secondary me-4'>Anterior</button>
        <button type="button" id="nextBtn" class='btn btn-success '>Próximo</button>
      </div>
    <% end %>

    <input type='hidden' value=<%= ride.to_college ? '1' : '0' %> id='hidden-to-college-value'>
    <input type='hidden' value=<%= ride.id %> id='hidden-ride-id'>

    <% unless ride.id.nil? %>
      <input type='hidden' value='<%= ride.destination.address %>' id='hidden-destination-address'>
      <input type='hidden' value='<%= ride.destination.city %>' id='hidden-destination-city'>

      <input type='hidden' value='<%= ride.departure.address %>' id='hidden-departure-address'>
      <input type='hidden' value='<%= ride.departure.city %>' id='hidden-departure-city'>

      <input type='hidden' value=<%= ride.college_id %> id='hidden-college-id'>
    <% end %>
  </div>
</section>

<%= javascript_pack_tag 'ride_form' %>

app/views/rides/_full_ride_card.html.erb
<div class='card mb-4 w-100'>
  <div class='card-body d-flex flex-row justify-content-between container align-items-center'>
    <div class='d-flex flex-column justify-content-between w-100 pe-2'>
      <div class='d-flex align-items-center mb-3'>
        <h6 class='card-title m-0 ms-2 me-2'>Origem: <%= address_format(@ride.departure) %></h6>
        <p class="fw-bold text-primary m-0"><%= @ride.to_college ? nil : "Campus" %></p>
        <p class="fw-bold text-danger m-0"><%= @ride.active? ? nil : "Desativado" %></p>
      </div>
      <div class='d-flex align-items-center mb-4'>
        <h6 class="card-title m-0 ms-2 me-2">Destino: <%= address_format(@ride.destination) %></h6>
        <p class="fw-bold text-primary m-0"><%= @ride.to_college ? "Campus" : "Campus" %></p>
      </div>
      <h6 class="card-subtitle mb-3 ms-2 text-muted">Data: <%= "#{@ride.date.strftime("%d/%m/%y")} - #{@ride.time.strftime("%R")}" %></h6>
      <h6 class="card-subtitle mb-3 ms-2 text-muted">Assentos totais: <%= @ride.seats %></h6>
      <h6 class="card-subtitle mb-3 ms-2 text-muted">Assentos disponives: <%= @ride.seats - @ride.number_of_passagers %></h6>
      <h6 class="card-subtitle mb-3 ms-2 text-muted">Preço: <%= @ride.price %></h6>
      <h6 class="card-subtitle mb-3 ms-2 text-muted">Motorista: <%= User.find(@ride.driver_id).name %></h6>
      <div class='divider mb-3 mt-0'></div>
      <h6 class="card-subtitle mb-3 ms-2 text-muted">Observação: <%= @ride.observation %></h6>
    </div>
    <div class='d-flex flex-column'>
      <% if @ride.driver_id == @logged_user.id %>
        <%= link_to 'Editar', edit_user_ride_path(@logged_user, @ride), class: 'btn btn-outline-warning mb-3' %>
        <% if @ride.active? %>
          <%= link_to 'Desativar', ride_toggle_active_path(@logged_user, @ride), data: {confirm: "Tem certeza?"}, class: 'btn btn-outline-danger' %>
        <% else %>
          <%= link_to 'Reativar', ride_toggle_active_path(@logged_user, @ride), data: {confirm: "Tem certeza?"}, class: 'btn btn-outline-success' %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class='card-footer'>
    <ol class='list-group list-group-flush'>
      <li class='list-group-item'>Origem: <%= address_format(@ride.departure) %></li>
      <% @ride.ordered_waypoints.each do |waypoint| %>
        <% next if waypoint.order == 0 %>
        <li class='list-group-item'><%= "Parada em #{address_format(waypoint)}" %></li>
      <% end %>
      <li class='list-group-item'>Destino: <%= address_format(@ride.destination) %></li>
    </ol>
  </div>
</div>

app/views/rides/_ride_card.html.erb
<div class='card mb-4'>
  <div class='card-body d-flex flex-row justify-content-between container align-items-center'>
    <div class='d-flex flex-column justify-content-between w-100 pe-2'>
      <div class='d-flex align-items-center mb-3'>
        <h6 class='card-title m-0 ms-2 me-2 departure-name'>Origem: <%= address_format(ride.departure) %></h6>
        <p class="fw-bold text-primary m-0"><%= ride.to_college ? nil : "Campus" %></p>
        <p class="fw-bold text-danger m-0"><%= ride.active? ? nil : "Desativado" %></p>
      </div>
      <div class='d-flex align-items-center mb-4'>
        <h6 class="card-title m-0 ms-2 me-2 destination-name">Destino: <%= address_format(ride.destination) %></h6>
        <p class="fw-bold text-primary m-0"><%= ride.to_college ? "Campus" : nil %></p>
      </div>
      <h6 class="card-subtitle mb-3 ms-2 text-muted ride-date" id='date'>Data: <%= "#{ride.date.strftime("%d-%m-%y")} - #{ride.time.strftime("%R")}" %></h6>
      <h6 class="card-subtitle mb-3 ms-2 text-muted">Assentos totais: <%= ride.seats %></h6>
      <h6 class="card-subtitle mb-3 ms-2 text-muted">Assentos disponives: <%= ride.seats - ride.number_of_passagers %></h6>
      <h6 class="card-subtitle mb-3 ms-2 text-muted">Preço: <%= ride.price %></h6>
      <h6 class="card-subtitle mb-3 ms-2 text-muted driver-name">Motorista: <%= User.find(ride.driver_id).name %></h6>
      <div class='divider mb-3 mt-0'></div>
      <h6 class="card-subtitle mb-3 ms-2 text-muted">Observação: <%= ride.observation %></h6>
    </div>
    <div class='d-flex flex-column'>
      <% if ride.driver_id == user.id %>
        <%= link_to 'Detalhes', user_ride_path(user, ride), class: 'btn btn-outline-primary mb-3' %>
        <%= link_to 'Editar', edit_user_ride_path(user, ride), class: 'btn btn-outline-warning mb-3' %>
        <% if ride.active? %>
          <%= link_to 'Desativar', ride_toggle_active_path(user, ride), data: {confirm: "Tem certeza?"}, class: 'btn btn-outline-danger' %>
        <% else %>
          <%= link_to 'Reativar', ride_toggle_active_path(user, ride), data: {confirm: "Tem certeza?"}, class: 'btn btn-outline-success' %>
        <% end %>
      <% else %>
        <%= link_to 'Detalhes', user_ride_path(ride.driver, ride), class: 'btn btn-outline-primary mb-3' %>
      <% end %>
    </div>
  </div>
</div>

app/views/rides/edit.html.erb
<h1>Editar Corrida</h1>

<%= render 'form', ride: @ride , user: @logged_user, url: user_ride_url(@logged_user, @ride) %>

app/views/rides/index.html.erb
<p id="notice"><%= notice %></p>
<div class='d-flex flex-row justify-content-between align-items-center'>
  <h1>Corridas</h1>
  <%= link_to 'Novo', new_user_ride_path(@logged_user), class: 'btn btn-primary' %>
</div>

<section class='d-flex justify-content-center'>  
  <ul class='w-75 p-3'>
    <% @rides.each do |ride| %>
      <%= render 'ride_card', {ride: ride, user: @user} %>
    <% end %>
  </ul>
</section>

app/views/rides/new.html.erb
<h1>Nova Corrida</h1>
<%= render 'form', ride: @ride, user: @logged_user, url: user_rides_url(@logged_user) %>

app/views/rides/search.html.erb
<h1>Procurar Caronas</h1> 
<%= form_with url: search_rides_url, method: :get do |form| %>
  <div class='d-flex align-items-end'>
    <!-- TEXT INPUTS -->
    <div class='d-flex align-items-center w-80'>
      <!-- DEPARTURE -->
      <div id='departure_text_field' class='me-3 w-100'>
        <p class='mb-2'>Partida:</p>
        <div class='input-group' id='departure-input'>
          <div class="input-group-text justify-content-start align-items-center">
            <%= form.label :departure_kind, "Campus", class: 'me-2 form-check-label'%>
            <%= form.radio_button :departure_kind, :college , class: 'form-check-input', type: 'checkbox', id: 'departure_kind' %>
          </div>
          <%= form.text_field :departure, class: 'form-control', type: 'text', onchange: 'validateInputs()' %>
        </div>
      </div>
      <!-- DESTINATION -->
      <div id='destination_text_field' class='me-4 w-100'>
        <p class='mb-2'>Destino:</p>
        <div class='input-group' id='destination-input'>
          <div class="input-group-text justify-content-start align-items-center">
            <%= form.label :departure_kind, "Campus", class: 'me-2 form-check-label'%>
            <%= form.radio_button :destination_kind, :college, class: 'form-check-input', type: 'checkbox', id: 'destination_kind' %>
          </div>
          <%= form.text_field :destination, class: 'form-control', type: 'text', onchange: 'validateInputs()' %>
        </div>
      </div>
    </div>

    <%= form.submit 'Procurar', class:'btn btn-outline-secondary', disabled: true, id:'commit-btn' %>
  </div>
<% end %>

<section class='d-flex justify-content-center'>  
  <ul class='w-75 p-3'>
    <% @rides.each do |ride| %>
      <%= render 'ride_card', {ride: ride, user: @logged_user} %>
    <% end %>
  </ul>
</section>
<%= javascript_pack_tag 'search_ride' %>

app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Detalhes da Carona</h1>

<%= render partial: 'full_ride_card' %>

<% if @ride.driver_id == @logged_user.id %>
  <%= link_to 'Voltar', user_rides_path(@logged_user), class: 'btn btn-secondary' %>
<% else %>
  <%= link_to 'Voltar', search_rides_path, class: 'btn btn-secondary' %>
<% end %>